import {
  Activity,
  Book,
  Coffee,
  Dumbbell,
  Heart,
  Music,
  Sun,
  Zap,
  Droplet,
  Brain,
  CheckCircle,
  X,
  Edit,
  Trash,
  Plus,
  Calendar,
  BarChart,
  Settings,
  LogOut,
  User,
  Home,
  Award,
  Trophy,
  Star,
  Flame,
  Target,
  Clock,
  Bell,
  HelpCircle,
  Info,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Search,
  Filter,
  RefreshCw,
  Download,
  Upload,
  ExternalLink,
  Loader,
  LucideProps,
} from "lucide-react";

export const Icons = {
  activity: Activity,
  book: Book,
  coffee: Coffee,
  dumbbell: Dumbbell,
  heart: Heart,
  music: Music,
  sun: Sun,
  zap: Zap,
  droplet: Droplet,
  brain: Brain,
  check: CheckCircle,
  close: X,
  edit: Edit,
  delete: Trash,
  add: Plus,
  calendar: Calendar,
  chart: BarChart,
  settings: Settings,
  logout: LogOut,
  user: User,
  home: Home,
  award: Award,
  trophy: Trophy,
  star: Star,
  flame: Flame,
  target: Target,
  clock: Clock,
  bell: Bell,
  help: HelpCircle,
  info: Info,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  menu: Menu,
  search: Search,
  filter: Filter,
  refresh: RefreshCw,
  download: Download,
  upload: Upload,
  externalLink: ExternalLink,
  spinner: Loader,
};

export type IconName = keyof typeof Icons;

export interface IconProps extends LucideProps {
  name: IconName;
  size?: number;
}

export function Icon({ name, size = 24, ...props }: IconProps) {
  const IconComponent = Icons[name];
  return <IconComponent size={size} {...props} />;
}
